language: clojure
lein: 2.8.1
# jdk:
#   - openjdk8    # oraclejdk8 no longer supported by TravisCI (or Oracle)
#   - openjdk11   # Don't fall for Oracle's trick: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

cache:
  directories:
  - .autoconf
  - $HOME/.m2

# Workaround for TravisCI's garbage openjdk10 base image
before_install:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then openssl aes-256-cbc -K $encrypted_4182063627e7_key -iv $encrypted_4182063627e7_iv -in tokens.tar.enc -out tokens.tar -d ; tar xvf tokens.tar; fi
  - if [[ $JAVA_HOME == *openjdk10* ]]; then rm "${JAVA_HOME}/lib/security/cacerts"; ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi

script: lein do git-info-edn, version, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"